name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: |
            raphaelalvares/minha-app-php:v1.0
            raphaelalvares/minha-app-php:latest
